# Generated by Django 4.2.2 on 2023-06-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cortex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HDF5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_shape', models.JSONField()),
                ('hdf5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.hdf5')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.cortex')),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.layer')),
                ('neural_network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.neuralnetwork')),
                ('post_nn', models.ManyToManyField(related_name='post_nn_configs', to='CortexBack.neuralnetwork')),
                ('pre_nn', models.ManyToManyField(related_name='pre_nn_configs', to='CortexBack.neuralnetwork')),
            ],
        ),
        migrations.AddField(
            model_name='cortex',
            name='layers',
            field=models.ManyToManyField(to='CortexBack.layer'),
        ),
    ]
