# Generated by Django 4.2.6 on 2023-10-09 14:26

from django.db import migrations, models
import django.db.models.deletion
import main_lib.iNeuralNetwork


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cortex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HDF5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_shape', models.JSONField()),
                ('hdf5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.hdf5')),
            ],
        ),
        migrations.CreateModel(
            name='TFLayerTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('possible_values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.cortex')),
            ],
        ),
        migrations.CreateModel(
            name='TFLayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('options', models.ManyToManyField(blank=True, to='CortexBack.tflayertypeoption')),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 'FIRST'), (1, 'MIDDLE'), (2, 'LAST')], default=1)),
                ('cortex', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CortexBack.cortex')),
                ('neural_network', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CortexBack.neuralnetwork')),
                ('next_NN', models.ManyToManyField(blank=True, to='CortexBack.neuralnetworkconfig')),
                ('previous_NN', models.ManyToManyField(blank=True, to='CortexBack.neuralnetworkconfig')),
            ],
            bases=(models.Model, main_lib.iNeuralNetwork.INeuralNetwork),
        ),
    ]
