# Generated by Django 4.2.5 on 2023-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CortexBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFLayerTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('possible_values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TFLayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('options', models.ManyToManyField(to='CortexBack.layer')),
            ],
        ),
    ]
