# Generated by Django 4.2.6 on 2023-10-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CortexBack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfoption',
            old_name='option_name',
            new_name='option_value',
        ),
        migrations.AlterField(
            model_name='layer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CortexBack.tflayertype'),
        ),
        migrations.AlterField(
            model_name='tfoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.tflayertypeoption'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='cortex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CortexBack.cortex'),
        ),
    ]
