# Generated by Django 4.2.5 on 2023-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CortexBack', '0002_tflayertypeoption_tflayertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tflayertype',
            name='options',
            field=models.ManyToManyField(to='CortexBack.tflayertypeoption'),
        ),
    ]
