# Generated by Django 4.2.5 on 2023-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CortexBack', '0003_alter_tflayertype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tflayertype',
            name='options',
            field=models.ManyToManyField(blank=True, to='CortexBack.tflayertypeoption'),
        ),
    ]
